### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by deoapp** [teguhpermadi/siakad#1]
Boss ini databasenya apa memang tidak lengkap?

**Comment by teguhpermadi** [comment]
saya pakai migration bukan pakai file sql

**Comment by deoapp** [comment]
Ada Tutorialnya mas?
Apakah saya harus satu2 untuk create DBnya mas?

**Comment by teguhpermadi** [comment]
belum saya buatkan tutorial mas, tp coba ikuti langkah ini

1. buat database dulu, sesuaikan nama database dengan file config database-nya
2. buka **localhost/siakad/migrate** untuk mengenerate otomatis semua tabel yg diperlukan
3. buka **localhost/siakad** kemudian login sebagai admin untuk memulai program

**Comment by ekohardi** [comment]
> belum saya buatkan tutorial mas, tp coba ikuti langkah ini
> 
> 1. buat database dulu, sesuaikan nama database dengan file config database-nya
> 2. buka **localhost/siakad/migrate** untuk mengenerate otomatis semua tabel yg diperlukan
> 3. buka **localhost/siakad** kemudian login sebagai admin untuk memulai program

username: administrator utk passnya apa gan?

**Comment by teguhpermadi** [comment]
lewat email mas

**Comment by Darpadi** [comment]
Izin minta passwordnya mas
darpady2@gmail.com
